### ISSUE TITLE
Pop Up crashes as soon it is pushed to UI 

### ISSUE THREAD

**Issue by ashishkumar070** [rotorgames/Rg.Plugins.Popup#486] opened 2019-10-22 17:29 UTC
With the recent update of Visual Studio and XCode the pop up crashes as soon as I try to open the pop up using `await PopupNavigation.Instance.PushAsync(SomePopUp);`

Tested on following device iOS iPad 13.1 & emulator OS version 13.2 

And I see people closing the issue on the previous threads.

```
Visual Studio Enterprise 2019 for Mac Version 8.3.4 (build 8)

Apple Developer Tools Xcode 11.1 (15405) Build 11A1027

Xamarin.iOS Version: 13.4.0.2 (Visual Studio Enterprise)

Operating System Mac OS X 10.15.0

Rg.PopUp.Plugin Version 1.2.0.223

Xamarin.Forms Version 3.6.0.264807
```

Stacktrace 

` at Rg.Plugins.Popup.Services.PopupNavigationImpl.PushAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00091] in C:\\projects\\rg-plugins-popup\\src\\Rg.Plugins.Popup\\Services\\PopupNavigationImpl.cs:86 \n  at VMSApp.Views.FillDetailsPage.OpenPurposePopUp (System.Object sender, Xamarin.Forms.FocusEventArgs e) [0x0000f] in /Users/ashish/Documents/Work \n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 \n  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/Foundation/NSAction.cs:178 \n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:86 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIKit/UIApplication.cs:65 \n  at VMSApp.iOS.Application.Main (System.String[] args) [0x00001] in /Users/ashish/Main.cs:17 "`

**Comment by ashishkumar070** [comment] 2019-10-24 17:57
@rotorgames Can you please check, all the iOS device will be affected !

**Comment by Sanketjo** [comment] 2019-10-31 13:37
Any updates on this issue , I am facing same error ... app is getting crash.

**Comment by piolo94** [comment] 2019-11-03 18:32
Same problem here with the latest stable version.
It happens more times than I want but not always, so I've found a barely acceptable workaround:

- put every navigation instance inside a try/catch and fire again the navigation in the catch branch if the action you want to perform is strictly mandatory
- the same above, but with the catch brand empty so the user is forced to repeat the operation

Please, work on this because it's blocking

**Comment by dmarjoram** [comment] 2019-12-09 21:36
My firebase testing on Android is ALL full of this.

android.runtime.JavaProxyThrowable: System.InvalidOperationException: The page has not been pushed yet or has been removed already
  at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemovePageAsync (Rg.Plugins.Popup.Pages.PopupPage page, System.Boolean animate) [0x00052] in <5ab9a1a9dc2a49aa9bac5b2ef3232ecc>:0 
  at ***.***.MessagePopup.HidePopup () [0x0007c] in <74463f15d63447ebaea26cbbbf4faca9>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <fb977718ab1c4d1b82462413c22796a5>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <b5df84bc5a6a41369981afcbda40e91f>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <b5df84bc5a6a41369981afcbda40e91f>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <b5df84bc5a6a41369981afcbda40e91f>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.34(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by alessandrofrancesconi** [comment] 2020-02-25 21:38
Any news about this?

**Comment by AbdellahOusrhireDev** [comment] 2020-03-31 08:42
@rotorgames please, this is a known issue, any news on when it will be fixed?

**Comment by alessandrofrancesconi** [comment] 2020-04-12 08:45
Problem still present in 2.0.0.2
Currently I'm stick with 1.1.5.188, this seems to be the last working release.

**Comment by LuckyDucko** [comment] 2020-04-17 11:02
hey @alessandrofrancesconi are you able to provide a minimal working version to aid in investigating this? I have not been able to create this issue

**Comment by bbenetskyy** [comment] 2021-03-13 19:57
Hi RG.Popups Team 

I can reproduce this error on `2.0.0.10`, in the beginning, it works, but later without any reason it stops and doesn't work anymore.

How can we solve it???

**Comment by LuckyDucko** [comment] 2021-03-14 22:00
@bbenetskyy are you able to provide a project to show this? I have not been able to recreate it so far

**Comment by prabh-62** [comment] 2021-03-15 22:52
Maybe pop all twice
```csharp
await Navigation.PopAllPopupAsync();
await Navigation.PopAllPopupAsync();
```

**Comment by bbenetskyy** [comment] 2021-04-05 05:33
After a deep investigation, I found what causes the problem - at my Popup, the first popup, I have a `ListView` with `CachingStrategy` Property. With `RetainElement` all works as excepted, but with other values - only this first popup just not shown on iOS. At Android, I don't face such limitation.

Solution - just have `CachingStrategy="RetainElement"` at `ListView`.

So @LuckyDucko, looks like the initial problem described at issue is not what I had and I can't reproduce the initial problem from this issue 🙂

**Comment by LuckyDucko** [comment] 2021-04-06 05:22
@bbenetskyy thank you for your feedback. Since this is quite an old issue, and people are not able to provide a reproducible copy, im going to close this for now. if someone can, I'll reopen

**Closed by LuckyDucko** 2021-04-06 05:22 UTC

**Comment by SuriGabi** [comment] 2022-02-13 08:46
HI LuckyDucko,

The problem still persists with the new version!
I have created a new project and I am using Rg.Plugins.Popup 2.1.0. 

If you use the sample code (see below) you can easily get the following error:
Rg.Plugins.Popup.Exceptions.RGPopupStackInvalidException: 'The page has not been pushed yet or has been removed already'
Version 1.1.5.188 did not have this error.

It this a sample:

MainActivity inserted line:
Rg.Plugins.Popup.Popup.Init(this);

Make new PopupPage view:
(XAML)
<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             x:Class="SCL.Dialogs.MessageBar"
             BackgroundColor="Transparent"
             InputTransparent="False"   
             BackgroundInputTransparent="True"
             HasSystemPadding="False"
             CloseWhenBackgroundIsClicked="True">
  <pages:PopupPage.Animation>
    <animations:MoveAnimation PositionIn="Top" PositionOut="Top"/>
  </pages:PopupPage.Animation>
    <StackLayout x:Name="slTitle" VerticalOptions="Start" BackgroundColor="Aqua">
    <Label x:Name="lTitle" Margin="10, 0, 0, 5" TextColor="White" VerticalOptions="EndAndExpand" HorizontalTextAlignment="Center" Text=""/>
  </StackLayout>
</pages:PopupPage>

(CS)
using System;
using System.Threading.Tasks;

using Xamarin.Forms;

using Rg.Plugins.Popup.Pages;
using Rg.Plugins.Popup.Services;

namespace SCL.Dialogs
{
    public partial class MessageBar : PopupPage
    {
        public MessageBar(string title, Color color)
        {
            InitializeComponent();

            var swipeTitle = new SwipeGestureRecognizer() { Direction =  SwipeDirection.Up };
            swipeTitle.Swiped += lTitle_Gestured;
            lTitle.GestureRecognizers.Add(swipeTitle);

            var tapTitle = new TapGestureRecognizer();
            tapTitle.Tapped += lTitle_Gestured;
            lTitle.GestureRecognizers.Add(tapTitle);

            lTitle.Text = title;
            slTitle.BackgroundColor = color;
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            HidePopup();
        }

        public async void lTitle_Gestured(object sender, EventArgs e)
        {
            await PopupNavigation.Instance.RemovePageAsync(this);
        }

        private async void HidePopup()
        {
            await Task.Delay(2000);
            await PopupNavigation.Instance.RemovePageAsync(this);
        }
    }
}

And create mainview add button with clicked event
        private async void Button_Clicked(object sender, EventArgs e)
        {
            await PopupNavigation.Instance.PushAsync(new MessageBar("POPUP!!! Please click repeatedly and crash!!!", Color.Red));
        }

Please click the button repeatedly and quickly. After 10-15 clicks you will get the crash

Thanks for yout help!
Have nice day!

**Comment by tbk21** [comment] 2022-02-24 09:50
Hi @SuriGabi , I am also experiencing the same issue on my side. The issue is only on iOS platform (v15+), with Xamarin forms (v5 +). The App just crashes when it hits line of code: await Navigation.PushPopupAsync(new ConfirmationDialog("Heading", "Question?", paramater));

Any luck in getting this issue resolved?
