### ISSUE TITLE
Forms 4.0 breaks iOS (and MacOS) platform(s)

### ISSUE THREAD

**Issue by melihercan** [rotorgames/Rg.Plugins.Popup#435] opened 2019-05-22 18:57 UTC
I upgraded to new Xamarin.Forms version 4.0 and observed that 
**await PopupNavigation.Instance.PopAsync(true);** 
call throws an exception on iOS and also on MacOS (I added the MacOS platform from pull request https://github.com/rotorgames/Rg.Plugins.Popup/pull/226).

I will provide more details soon.

**Comment by melihercan** [comment] 2019-05-23 05:29
Sorry the exception on iOS was my fault (due to a custom renderer) and there is no issue on iOS. 

But the MacOS exception is still there. It throws the following exception:

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.MacOS.ViewRenderer`2[TView,TNativeView].SetNativeControl (TNativeView uiview) [0x00046] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.ImageRenderer.OnElementChanged (Xamarin.Forms.Platform.MacOS.ElementChangedEventArgs`1[TElement] e) [0x0000e] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x0012a] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x0008c] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.ViewRenderer`2[TView,TNativeView].Dispose (System.Boolean disposing) [0x0005c] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.ImageRenderer.Dispose (System.Boolean disposing) [0x00035] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Foundation.NSObject.Dispose () [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.8.0.0/src/Xamarin.Mac/Foundation/NSObject2.cs:147
  at Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose () [0x00000] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Foundation.NSObject.Dispose () [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.8.0.0/src/Xamarin.Mac/Foundation/NSObject2.cs:147
  at Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose (System.Boolean disposing) [0x0003f] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose () [0x00000] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Xamarin.Forms.Platform.MacOS.VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) [0x00058] in <1121785e0c0f419ca48a1e554c79792c>:0
  at Foundation.NSObject.Dispose () [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.8.0.0/src/Xamarin.Mac/Foundation/NSObject2.cs:147
  at Rg.Plugins.Popup.Mac.Extensions.PlatformExtension.DisposeModelAndChildrenRenderers (Xamarin.Forms.VisualElement view) [0x00042] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup.Mac/Extensions/PlatformExtension.cs:47
  at Rg.Plugins.Popup.Mac.Impl.PopupPlatformMac.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x00014] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup.Mac/Impl/PopupPlatformMac.cs:43
  at Rg.Plugins.Popup.Services.PopupNavigationImpl.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) [0x0000f] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:134
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass10_0.<RemovePageAsync>b__0 () [0x0012a] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:115
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafe>b__0 () [0x0002e] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:165
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass8_0.<PopAsync>b__0 () [0x00095] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:79
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafe>b__0 () [0x0002e] in /Users/melihercan/svn/XF/nuget/src/Rg.Plugin.Popup.Forms4/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs:165
  at Monitor.Popups.InfoPopup.OnOkButton (System.Object sender, System.EventArgs e) [0x00020] in /Users/melihercan/svn/XF/Monitor/Monitor/Popups/InfoPopup.xaml.cs:55
....

**Comment by roncyrier** [comment] 2019-06-23 19:05
I'm getting the same issue.  Any resolution?

**Comment by rotorgames** [comment] 2019-07-23 09:46
Currently, this plugin doesn't support MacOS. I'm going to do it in the future but not right now because there are some errors in the plugin and I have to fix them.

**Comment by amirvenus** [comment] 2019-08-10 13:52
It has been a while that I am waiting for macOS. 

I hope it is released soon.  Keep up the good work!

**Comment by KalyanXamarin** [comment] 2019-08-27 11:04
@rotorgames  the same issue exit in iOS 13. Any updates?

**Comment by rotorgames** [comment] 2019-10-03 11:26
I think it's duplicate of #459. If it's not, please reopen it.

**Closed by rotorgames** 2019-10-03 11:26 UTC
