### ISSUE TITLE
PopupPage never destroyed on IOS (Android maybe)

### ISSUE THREAD

**Issue by mrmiagi0101** [rotorgames/Rg.Plugins.Popup#112] opened 2017-04-26 15:45 UTC
Hi,
I created a very simple example, where you can see destructor of popupPage is never called. 
I tested with:
Xamarin Forms 2.3.4.231 (latest stable) and 2.3.5.233-pre1
RG.Plugins.Popup 1.0.4
Iphone 5s with IOS 10.3.1
Samsung A5 (2016) with Android 6.0.1

On IOS and Android the popupPage gets never destroyed! But with a small fix on Android it works. But with IOS no luck. Maybe you can investigate what happens?

Sample:
`public partial class AboutPage : ContentPage
  {
    public AboutPage()
    {
      InitializeComponent();
      this.TestBtn.Clicked += TestBtn_Clicked;
      this.RamBtn.Clicked += RamBtn_Clicked;
    }
   
    private async void TestBtn_Clicked(object sender, System.EventArgs e)
    {
      var page = new CustomPopupPage();
      await PopupNavigation.PushAsync(page, false);
    }

    private void RamBtn_Clicked(object sender, System.EventArgs e)
    {
      GC.Collect();
      GC.WaitForPendingFinalizers();
      GC.Collect();
    }

    public class CustomPopupPage:PopupPage
    {
      public CustomPopupPage()
      {
        var btn = new Button() { Text = "Close" };
        btn.Clicked += Btn_Clicked;
        this.Content = btn;
      }

      private void Btn_Clicked(object sender, EventArgs e)
      {
        PopupNavigation.PopAllAsync(false);
        // This line fixes leak in Android, but not IOS!
        this.Parent = null;
      }

      ~CustomPopupPage()
      {
        // Set breakpoint here: Android with fix is working, but not IOS!
      }
    }`

**Comment by rotorgames** [comment] 2017-04-26 17:48
@mrmiagi0101 Hi. Thank you for question. Yes, this plugin has memory leaks now, but I'm fixing it now. I has fixed it on iOS, and I will fix it on Android soon. 

All memory leaks will be fixed in 1.1.0

**Comment by rotorgames** [comment] 2017-04-26 17:49
See #26

**Comment by mrmiagi0101** [comment] 2017-04-27 06:45
Ok, thanks. Can you say when it is possible to get a fixed version?

**Comment by rotorgames** [comment] 2017-04-27 06:56
@mrmiagi0101 I can't. I'm doing it now.

**Comment by EmilAlipiev** [comment] 2017-05-05 22:37
Is there a workaround until you get this fixed? should we always collect it when it is popped? i was wondering why my app is getting slower when I use popups.

**Comment by rotorgames** [comment] 2017-05-06 12:57
@EmilAlipiev Hello. You can't do anything. The source of problem is in the core. The popup plugin should destroy all renderers in the children. This will be global change. I'm working on it.

**Comment by EmilAlipiev** [comment] 2017-05-08 09:57
@rotorgames thanks for your feedback. I am eagerly looking forward to it. let me know if we can help you somehow. Best Regards.

**Comment by justwooper** [comment] 2017-05-11 18:41
Hi, I am experimenting this problem too, when my app opens more than 3 popups it crashes, probably because the memory, it is an awesome work by the way, hope you can release an update soon

**Comment by rotorgames** [comment] 2017-05-11 18:43
@justwooper I have fixed memory leaks on iOS, but I can't publish new release right now, I should make more works with layouts and navigation. Please wait.

**Comment by justwooper** [comment] 2017-05-11 19:56
@rotorgames yes its ok, I can wait, I will try @mrmiagi0101 solution in the mean time

**Comment by EmilAlipiev** [comment] 2017-05-11 22:18
Is that mainly occurring on IOS? have you seen any issue on Android also?

**Comment by mrmiagi0101** [comment] 2017-05-12 06:20
At the moment on both OS.

**Comment by rotorgames** [comment] 2017-05-12 11:39
@EmilAlipiev @mrmiagi0101 Yes, Android and iOS have memory leaks.

**Comment by rotorgames** [comment] 2017-05-13 18:59
This issue was fixed in v1.1.0-pre. Please test it and tell me about your tests. Thank you.

**Closed by rotorgames** 2017-05-13 18:59 UTC
Labels: bug, confirm

**Comment by CodeSpeak11** [comment] 2017-05-14 14:41
Thank you for creating such an outstanding plugin!  I've started testing and have a question. I notice that PopupNavigation.PopAsync, PushAsync etc are marked obsolete. When I replace all of these with PopupNavigation.Instance.PopAsync, PushAsync etc, I get an unhandled exception. Perhaps I'm not understanding the recommended usage pattern

PopupNavigation.PopAllAsync(true);

changed to

PopupNavigation.Instance.PopAllAsync(true);

Should I be newing up my own instance of the IPopupNavigation interface. Most importantly, is this change necessary to avoid the memory leak problem you are trying to address?

**Comment by rotorgames** [comment] 2017-05-14 15:11
@CodeSpeak11 Hi. Thank you for the questions. 

1. Can you give the stack trace of the exception?
2. `PopupNavigation.Instance` is not required for using for fixing memory leaks but it will be better for the MVVM pattern and testing

**Comment by CodeSpeak11** [comment] 2017-05-14 15:22
will try loading symbols of your code to get around "external code" block on exception trace. App is working great w/o instance so will be reverting to not use Instance after sending stack  trace if I can get more details.

**Comment by rotorgames** [comment] 2017-05-14 15:26
@CodeSpeak11 This doesn't matter. PopupNavigation.PushAsync uses PopupNavigation.Instance.PushAsync also. You will not see difference.

**Comment by rotorgames** [comment] 2017-05-14 15:27
@CodeSpeak11 P.S. You can use `PopupNavigation` without `Instance`. I will not cut the static methods soon!

**Comment by CodeSpeak11** [comment] 2017-05-14 15:33
ok, thank you. I will revert my code and resume testing. As mentioned, I saw no problems after the upgrade until I switched to using Instance but didn't complete my testing on IOS.

**Comment by CodeSpeak11** [comment] 2017-05-14 18:54
Sorry for delay, it is a Mothers Day holiday here in the States. Note I am in the process of moving the ItemSelected eventhandler into the viewmodel but for now, it is in the code behind. 

 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/corlib/System.Diagnostics/Debugger.cs:122,4	C#
 	0x38 in object.b25f668a-b595-4a86-84fb-ed831262f321	C#
 	0x38 in System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<MyApp.App.Views.ItemsPage.<ListView_ItemSelected>d__10> at /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84,17	C#
 	0x38 in MyApp.App.Views.ItemsPage.ListView_ItemSelected	C#
 	0x1C in Xamarin.Forms.ListView.OnSelectedItemChanged at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\ListView.cs:588,5	C#
 	0x111 in Xamarin.Forms.BindableObject.SetValueActual at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:584,6	C#
 	0x154 in Xamarin.Forms.BindableObject.SetValueCore at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:378,5	C#
 	0x5 in Xamarin.Forms.BindableObject.SetValueCore at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:324,4	C#
 	0x55 in Xamarin.Forms.ListView.NotifyRowTapped at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\ListView.cs:408,4	C#
 	0x27 in Xamarin.Forms.ListView.NotifyRowTapped at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\ListView.cs:425,5	C#
 	0x3 in Xamarin.Forms.ListView.Xamarin.Forms.IListViewController.NotifyRowTapped at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\ListView.cs:430,4	C#
 	0x5F in Xamarin.Forms.Platform.Android.ListViewAdapter.HandleItemClick at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:383,4	C#
 	0x34 in Xamarin.Forms.Platform.Android.CellAdapter.OnItemClick at C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\CellAdapter.cs:142,5	C#
 	0x20 in Android.Widget.AdapterView.IOnItemClickListenerInvoker.n_OnItemClick_Landroid_widget_AdapterView_Landroid_view_View_IJ at /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Widget.AdapterView.cs:215,5	C#
 	0x29 in object.b25f668a-b595-4a86-84fb-ed831262f321	C#

**Comment by rotorgames** [comment] 2017-05-14 20:01
@CodeSpeak11 Can you show a part of code where you invoke PopAllAsync with Instance?

**Comment by CodeSpeak11** [comment] 2017-05-14 23:19
Not using PopAllAsync at all. I was at one point but don't know why I switched back to PopAsync

**Comment by rotorgames** [comment] 2017-05-15 03:29
@CodeSpeak11 Please show a part of code where you have an exception.

**Comment by CodeSpeak11** [comment] 2017-05-15 04:28
Just adding ".Instance" in the two places below was enough to cause the app to crash (stack trace shown above). Nothing else changed.

<?xml version="1.0" encoding="utf-8" ?>
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
            xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
            x:Class="MetaKb.App.Views.ItemPopupMenu">
    <pages:PopupPage.Resources>
        <ResourceDictionary>
            <Style x:Key="EntryStyle" TargetType="Entry">
                <Setter Property="PlaceholderColor" Value="#9cdaf1"/>
                <Setter Property="TextColor" Value="#7dbbe6"/>
            </Style>
        </ResourceDictionary>
    </pages:PopupPage.Resources>
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation
    PositionIn="Right"
    PositionOut="Right"
    ScaleIn="1"
    ScaleOut="0.7"
    DurationIn="360"
    EasingIn="SinIn"/>
    </pages:PopupPage.Animation>
    <ScrollView  HorizontalOptions="EndAndExpand"    VerticalOptions="StartAndExpand">
        <AbsoluteLayout>
            <Frame 
            x:Name="FrameContainer"
            Margin="0,20,0,0"
                 Padding="5,0,0,0"
            WidthRequest="345"
            HeightRequest="71"
            HorizontalOptions="EndAndExpand"
            VerticalOptions="CenterAndExpand"
            BackgroundColor="White">
                <StackLayout IsClippedToBounds="True" Spacing="3" Orientation="Horizontal">
                                        <Button Image="trash.png" Command="{Binding OptionCllckedCommand}"  CommandParameter="DeleteItem" WidthRequest="65"></Button>
                </StackLayout>
            </Frame>
        </AbsoluteLayout>
    </ScrollView>
</pages:PopupPage>

async public Task DeleteItem(BlinkItem item)
        {
            try
            {
                //pop initial popup form off stack
                await PopupNavigation.Instance.PopAsync(true);
                //display confirmation popup dialog
                await PopupNavigation.Instance.PushAsync(new YesNoConfirmPage());
            }

**Comment by rotorgames** [comment] 2017-05-15 04:38
@CodeSpeak11 Sorry but I can't reproduce it on my demo project. Can you give me sample project where you have this exception? It will help me so much.

**Comment by CodeSpeak11** [comment] 2017-05-15 04:51
I will attempt to create a simple repro case based on my code to avoid NDA issues. Eta 30 min.

**Comment by CodeSpeak11** [comment] 2017-05-15 05:51
I have created various iterations of my app and it appears that removing part of my app solves whatever problem is causing the exceptions. My repro case includes extensive usage of your plugin, so if it was a problem with your code, it should have repro'd. 

I am still fairly new to Xamarin and early on in my app, prototyping features, experimenting with UI design. At this point I would consider this a no repro. I will continue to add features to the repro to try and see what breaks it. 

FYI, I am using VS2017 enterprise see below and version 2.3.4.224 of Xamarin.Forms.

Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Xamarin   4.3.0.784 (73f58d6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   7.1.0.41 (9578cdc)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   10.4.0.123 (35d1ccd)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by rotorgames** [comment] 2017-05-15 05:53
@CodeSpeak11 Ok. If you have new exceptions, please tell me about it. Thank you.

**Comment by rotorgames** [comment] 2017-05-16 17:49
Ref #116
