### ISSUE TITLE
Dismiss Popup On Scroll down

### ISSUE THREAD

**Issue by arahmancsd** [rotorgames/Rg.Plugins.Popup#656] opened 2021-03-06 12:54 UTC
I am looking to dismiss the pop up when user scrolls down. However, it seems that the ScrollView Scrolled event doesen't fire.

```
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             xmlns:animations="clr-namespace:Rg.Plugins.Popup.Animations;assembly=Rg.Plugins.Popup"
             HasSystemPadding="True"
             CloseWhenBackgroundIsClicked="True"
             x:Name="MyPage"
             x:Class="wQuran.Views.Today.MyDaySettingsPopupPage">
    <pages:PopupPage.Animation>
        <animations:ScaleAnimation 
            PositionIn="Bottom"
            PositionOut="Bottom"
            DurationIn="400"
            DurationOut="300"
            EasingIn="SinOut"
            EasingOut="SinIn"
            HasBackgroundAnimation="True"/>
    </pages:PopupPage.Animation>
    <ScrollView Scrolled="ScrollView_Scrolled" VerticalOptions="End">
        <Frame CornerRadius="10" IsClippedToBounds="True" VerticalOptions="FillAndExpand">
            <StackLayout HeightRequest="300" VerticalOptions="Fill">
                <Label Text="Hello" HorizontalOptions="Center"/>
            </StackLayout>
        </Frame>
    </ScrollView>
</pages:PopupPage>

private void ScrollView_Scrolled(object sender, Xamarin.Forms.ScrolledEventArgs e)
        {
            if (e.ScrollY > 100)
            {
                itemViewModel.CloseDialogCommand.Execute(null); 
                // closes the popup PopupNavigation.Instance.PopAsync();
            }
        }
```

The scrolled event doesn't fire at all.

**Version**: 2.0.0.10

**Expected**:
Scrolled event should fire

**Actual**:
Scrolled event doesn't fire.

**Comment by LuckyDucko** [comment] 2021-03-12 00:33
hey @arahmancsd could you provide a complete sample project for me to work on. I understand if its a hassle, but it just ensures that you can recreate it on its complete own. 

Also, are you able to connect it to a different event and make it fire. Say, put a button on the page and try it that way. Just to confirm that `itemViewModel.CloseDialogCommand.Execute(null); ` is working as intended

**Comment by arahmancsd** [comment] 2021-03-12 17:50
@LuckyDucko I have created a sample project in [gitHub](https://github.com/arahmancsd/RgPluginDismissOnScrollSample). The idea is to make the pop up scrollable (up and down) like a native dialog in iOS platform. However, with this code the scroll doesn't work. I found the scroll only works if I add properly filled collection view in the design.

**Comment by LuckyDucko** [comment] 2021-03-30 00:56
@arahmancsd sorry for the late reply.

So it seems on iOS simulator, your sample will as soon as it opens fire the scrolled event with -20, and then with 0. closing the dialog instantly as well.

I commented out the scrollY code and tested again, however, a scrollview will not be able to scroll if you do not have content that is larger than the scrollview. So I changed the scrollview height to 200

now I have something 'working' as shown in this video
https://user-images.githubusercontent.com/17778102/112917620-c136c200-914e-11eb-82b6-680125a2095f.mp4

It would seem that, since you are unable to scroll, the ScrollY would not change, so you couldn't activate your closing code. 

Closing this as It isnt an issue with Rg.Plugins.Popup, however, @ me if you have any more concerns

**Closed as completed by LuckyDucko** 2021-03-30 00:56 UTC
Labels: bug, verify
