### ISSUE TITLE
Linker issues with Queue

### ISSUE THREAD

**Issue by Feierabend-LSS** [rotorgames/Rg.Plugins.Popup#577] opened 2020-09-07 08:51 UTC
## 🐛 Bug Report

When archiving with Linking set to Sdk Assemblies only it fails with 

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Collections.Generic.Queue`1' (defined in assembly 'Rg.Plugins.Popup, Version=2.0.0.5, Culture=neutral, PublicKeyToken=null') with scope 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Collections.Generic.Queue`1
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	i40.TestClient.Xamarin.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2129

and when linking is set to Sdk and User Assemblies it compiles, archives and distributes but will crash on startup.
If Linking is set to None it works. Is there a way to allow linking?

### Reproduction steps
Install Rg.Plugins.Popup NuGet
Set Linking to Sdk Assemblies only or Sdk and User Assemblies
Archive Xamarin.Android project

### Configuration

**Version:** 2.0.0.5
**Android SDK Compile:** 9.0
**Xamarin Forms:** 4.8.0.1364
Visual Studio Professional 2017 15.9.23

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment] 2020-09-08 07:17
hey @Feierabend-LSS 

I am unable to reproduce this, however this [issue](https://github.com/rotorgames/Rg.Plugins.Popup/issues/540) seems quite similar to yours, are you able to update your Xamarin.Android SDK version to something newer?

Perhaps moving to Visual Studio 2019 may help, as Visual studio 2017 support will be [phased out in the near future](https://github.com/xamarin/Xamarin.Forms/issues/11857)

**Comment by Feierabend-LSS** [comment] 2020-09-08 07:22
Hey @LuckyDucko,

thanks for the reply.
Unfortunately I cannot, we're on VS2017 and afaik SDK10 is VS2019 only

**Comment by LuckyDucko** [comment] 2020-09-08 07:50
@Feierabend-LSS does making the linker skip RG.Plugins.Popup help 
eg 		`<AndroidLinkSkip>Rg.Plugins.Popup;</AndroidLinkSkip>`

**Comment by Feierabend-LSS** [comment] 2020-09-08 11:22
@LuckyDucko No, still the same error.
I've also attached a Sample Test Solution, since you said you were unable to reproduce it. Error happens when compiling the TestApp.Android project in Release - Any CPU
[TestApp.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/5187955/TestApp.zip)

**Comment by LuckyDucko** [comment] 2020-09-09 22:56
hey @Feierabend-LSS I was able to build this without any changes on VS4Mac, release mode.
it seems the VS version may be to blame.

**Comment by Feierabend-LSS** [comment] 2020-09-10 05:46
Hey @LuckyDucko  thanks for the help and checking again. I'll bring this up and see if we can change.
For future reference I've edited the VS version in the op.

**Closed as completed** 2020-09-14 07:55 UTC

**Comment by hadwanihardik** [comment] 2020-09-18 10:21
@LuckyDucko I am also using visual studio for mac. can u tell me what settings u did in able to make archive for release mode.

**Comment by LuckyDucko** [comment] 2020-09-20 23:15
@hadwanihardik I did nothing special or different. simply opened the project linked above, built and archived in release. what errors do you have?
