### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by abdulkhn8** [rotorgames/Rg.Plugins.Popup#405] opened 2019-02-20 08:39 UTC

**Comment by abdulkhn8** [comment] 2019-02-20 08:39
at Rg.Plugins.Popup.IOS.Impl.PopupPlatformIos+<RemoveAsync>d__10.MoveNext () [0x001ab] in <9cde9985cfe5453d836575ce17f47cbb>:0 
--- End of stack trace from previous location where exception was thrown ---
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<RemoveAsync>d__12.MoveNext () [0x00028] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:134 
--- End of stack trace from previous location where exception was thrown ---
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass10_0+<<RemovePageAsync>b__0>d.MoveNext () [0x000e2] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:115 
--- End of stack trace from previous location where exception was thrown ---
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0+<<InvokeThreadSafty>b__0>d.MoveNext () [0x00022] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:163 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1023 
  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/Foundation/NSAction.cs:178 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIApplication.cs:63 
  at omya.iOS.Application.Main (System.String[] args) [0x00001] in /Users/abdul/Projects/New_Branch/omya-app/omya.iOS/Main.cs:17

**Comment by EmilAlipiev** [comment] 2019-02-27 02:26
do you get that on PopAllPopupAsync? I am seeing similar exception on PopAllPopupAsync

**Comment by rotorgames** [comment] 2019-05-11 17:22
@abdulkhn8 Could you give me a full stacktrace or create a simple project where I can replicate this issue?

**Comment by w-brunette** [comment] 2019-10-03 13:15
I'm with the same problem.

**Comment by rotorgames** [comment] 2019-10-03 14:27
I think it's duplicate of #459. If it's not, please reopen it.

**Closed by rotorgames** 2019-10-03 14:27 UTC
Labels: bug, need-review
