### ISSUE TITLE
Popup is disapearing after 2sec in IOS 13

### ISSUE THREAD

**Issue by Hayko97** [rotorgames/Rg.Plugins.Popup#470] opened 2019-09-30 09:30 UTC
When we have a background process in application which always running(Just have a background Thread which always doing something). After opening the popup it disappears after 2sec in IOS 13.

**Comment by hoangwy** [comment] 2019-09-30 11:21
Same here, Please update

**Comment by JKennedy24** [comment] 2019-09-30 12:36
is this a duplicate of https://github.com/rotorgames/Rg.Plugins.Popup/issues/459?

**Comment by TGlev** [comment] 2019-09-30 13:03
Yes @JKennedy24 its a dupe of #459

**Comment by Hayko97** [comment] 2019-10-01 09:23
#459 About app crashing when you call Init function.It is not duplicate please read the description I updated it.

**Comment by rotorgames** [comment] 2019-10-03 10:55
Duplicate #459

**Closed by rotorgames** 2019-10-03 10:55 UTC
