### ISSUE TITLE
Animations on iOS

### ISSUE THREAD

**Issue by taublast** [rotorgames/Rg.Plugins.Popup#404] opened 2019-02-19 12:37 UTC
Hi, this happens only on iOS:

Encountered this with the following animation but it might be same issue with any:

```
    <pages:PopupPage.Animation>
        <animations:MoveAnimation
            DurationIn="200"
            DurationOut="200"
            EasingIn="SinOut"
            EasingOut="SinIn"
            HasBackgroundAnimation="True"
            PositionIn="Left"
            PositionOut="Left" />
    </pages:PopupPage.Animation>
```
What happens on iOS is that it shows the non-translated content in the middle of the screen for a fractal of second, creating a flicker, then correctly translates content out of the screen and starts animating it inside to 0,0.

This is due to xamarin not updating the content translation set in a non-ui thread, it just draws the untranslated content, then animates. Adding just `await Task.Delay(1);` solves it, the execution jumps into ui thread and updates the out-of-screen translation.

So for the the above animation the flicker-free code is:

```
 public async override Task Appearing(View content, PopupPage page)
        {
            var taskList = new List<Task>();

            taskList.Add(base.Appearing(content, page));

            if (content != null)
            {
                var topOffset = GetTopOffset(content, page);
                var leftOffset = GetLeftOffset(content, page);

                if (PositionIn == MoveAnimationOptions.Top)
                {
                    content.TranslationY = -topOffset;
                }
                else if (PositionIn == MoveAnimationOptions.Bottom)
                {
                    content.TranslationY = topOffset;
                }
                else if (PositionIn == MoveAnimationOptions.Left)
                {
                    content.TranslationX = -leftOffset;
                }
                else if (PositionIn == MoveAnimationOptions.Right)
                {
                    content.TranslationX = leftOffset;
                }
                await Task.Delay(1);
                taskList.Add(content.TranslateTo(_defaultTranslationX, _defaultTranslationY, DurationIn, EasingIn));
            }

```

**Comment by rotorgames** [comment] 2019-02-28 22:57
@taublast What version of the plugin do you use?

**Comment by taublast** [comment] 2019-03-01 13:19
It was all the latest nuget version 10 days ago, until i forked the code to solve it.. Can't tell the version anymore as i'm just using the modified forked code now. 

There are some more issues like the animation system is actually designed having in mind that popup will be destroyed after final animation. But if you keep it in memory and just push the existing popup that have already been animated there's another problem.
Imagine the view inside the popup having a translation of 0,0. When starting animation the engine gets view defaultTranslationX, defaultTranslationY (https://github.com/rotorgames/Rg.Plugins.Popup/blob/70ef35fc3758354f5a89beed26eb2aaddb196f8f/src/Rg.Plugins.Popup/Animations/MoveAnimation.cs#L12) that are zero and start animating. Let's say the final X have to be 100. But if you close the popup when the translations was at 50, the next push will start to animate from 50 too 100 instead of from 0 to 100. This can be fixed by moving this variables from the animation level to the popup page level, so they are initialized once when the popup is created and not everytime the animation starts.

Also i'm forced to stay on modified code because i just can't beat random exceptions that plugin throws (https://github.com/rotorgames/Rg.Plugins.Popup/blob/70ef35fc3758354f5a89beed26eb2aaddb196f8f/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L76) when trying to pop a page when popupnavigation stack is empty, it happens randomly, so i just disabled 'throw'. Have tried to try-catch everywhere in my code, it just doesn't work, exceptions are breaking in some threads out of my blocks.. From what i found in internet i'm not alone with this issue, frankly can't see a point of throwing an exception for a pop..

Great plugin, thank you for your efforts!

**Comment by flaviosuardi** [comment] 2019-03-26 16:45
Great fix @taublast and great plugin @rotorgames!
Do you @rotorgames have in mind to release a new version with this fix?

**Comment by patchandthat** [comment] 2019-03-28 14:22
If it sheds any light on the issue, this seems to be present from Xamarin.Forms 3.5 and onwards.  I have this issue both in popups and in other areas of my app that have animations.  Downgrading to Xamarin.Forms 3.4 is also a viable workaround.

There doesn't appear to be a Xamarin.Forms issue raised for this at the moment, but I intend to raise it once I'm done digging around.

Thanks @taublast for the workaround.

**Comment by flaviosuardi** [comment] 2019-03-29 08:57
@patchandthat downgrading to Xamarin.Forms 3.4 did not solve the problem.

**Comment by rotorgames** [comment] 2019-04-01 08:36
Can someone give me an example of xaml file which has this issue? I can't replicate it. It always is fine for me. @taublast ?

**Comment by rotorgames** [comment] 2019-04-01 08:51
> There are some more issues like the animation system is actually designed having in mind that popup will be destroyed after final animation. But if you keep it in memory and just push the existing popup that have already been animated there's another problem.

In new version which I'm preparing it's not possible because a popup can't be closed before appearing and disappearing animations are finished.

**Comment by taublast** [comment] 2019-04-01 09:43
It was on iOS only:

> 
> <?xml version="1.0" encoding="UTF-8" ?>
> <pages:PopupPage
>     x:Class="AppoMobi.PopupMenu"
>     xmlns="http://xamarin.com/schemas/2014/forms"
>     xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>     
>     ...
> 
>     BackgroundColor="#99000000"    
>      HasSystemPadding="False">
> 
>     <pages:PopupPage.Animation>
>         <animations:MoveAnimation
>             DurationIn="200"
>             DurationOut="200"
>             EasingIn="SinOut"
>             EasingOut="SinIn"
>             HasBackgroundAnimation="True"
>             PositionIn="Left"
>             PositionOut="Left" />
>     </pages:PopupPage.Animation>
> 
>     <ContentPage.Content>
> 
>         <Grid 
>             x:Name="Panel"
>             VerticalOptions="FillAndExpand" WidthRequest="300" HorizontalOptions="Start">
> 
> 
> ...
> 
>         </Grid>
>     </ContentPage.Content>
> 
> </pages:PopupPage>

**Comment by meiotoha** [comment] 2019-04-01 10:01
all latest packages. iOS 12.2.

@rotorgames 
This is a sample page.It shows frequently in my iOS simulator.
And maybe  the layout  is more complex, the problem show more frequently ?
```
    <pages:PopupPage.Animation>
        <animations:MoveAnimation PositionIn="Left"
                                  PositionOut="Left"
                                  DurationIn="500"
                                  DurationOut="500" />
    </pages:PopupPage.Animation>
    <StackLayout HorizontalOptions="Start"
                 WidthRequest="400"
                 BackgroundColor="WhiteSmoke">
            <StackLayout>
                <Label FontSize="48" Text="Welcome!" />
                <!-- this stacklayout -->
                <StackLayout HorizontalOptions="CenterAndExpand">
                    <Label Text="T1" />
                </StackLayout>
            </StackLayout>
    </StackLayout>
```

**Comment by rotorgames** [comment] 2019-04-01 10:42
I have replicated it. It happens only with Xamarin.Forms 3.5+.

**Comment by patchandthat** [comment] 2019-04-01 11:12
@rotorgames FYI I have not raised the issue with the Xamarin.Forms team as I was struggling to put together a minimal example solution to reproduce the bug.  I've used the `Delay(1)` workaround for now as I've got a lot of things to deal with at the moment.

**Comment by rotorgames** [comment] 2019-04-01 11:17
Ok, guys. I need more time to find out what's wrong with the new version of Xamarin.Forms. I think that Xamarin.Forms doesn't render views with `IsVisible = false`. Maybe it's a good optimization but it breakes animations for this plugin. I will try to figure out a better solution ASAP. 

Thanks guys.

**Comment by rotorgames** [comment] 2019-05-11 19:21
@taublast I think I have fixed this issue. Could you test the last version in Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99

Thanks.

**Comment by taublast** [comment] 2019-05-12 16:15
Yes, by monday will do, thanks for you efforts!

**Comment by rotorgames** [comment] 2019-05-14 04:47
@taublast Any news?

**Comment by taublast** [comment] 2019-05-15 05:55
222222222222222222222222222222222222222222222222222222222222222222 KIAQ

**Comment by rotorgames** [comment] 2019-05-15 05:58
@taublast Cool. Check it please on a real device and if it is fine I'll close this issue. Thanks.

**Comment by flaviosuardi** [comment] 2019-05-15 09:13
@rotorgames I try on iPhoneXs with iOS 12.2 and it works like a charm!
Thanks @rotorgames!

**Comment by rotorgames** [comment] 2019-05-19 07:34
@flaviosuardi Nice to hear it.

**Closed by rotorgames** 2019-05-19 07:34 UTC
Labels: bug, confirmed, fixed

**Comment by Miksier** [comment] 2019-09-11 11:44
@rotorgames 
First, a very nice plugin and a lot of work put into it.
I see that the commit fixing it is not on the nuget.com. Is there any date we can expect to have it?

Thanks.

**Comment by lancer1977** [comment] 2019-10-01 21:10
https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99
If you add this to your nuget sources you can update to the latest version and I have found it does fix my issue. Good luck!

@rotorgames  thanks for the hard work and the prompt response. Could use a release on Nuget.org still.

**Comment by jmichas** [comment] 2019-12-18 00:19
I'm using version 1.2.0.223 with Prism 7.2.0.1422 and I am still having the flicker problem using the move animation. Is this fix in the version I am using?

**Comment by Samidolla** [comment] 2020-11-23 11:27
hwo do you use Rg animation in c# programmatically
