### ISSUE TITLE
Popup problem when android device animation off

### ISSUE THREAD

**Issue by leeanpeng** [rotorgames/Rg.Plugins.Popup#136] opened 2017-06-16 01:14 UTC
Hi, when I set the device animation off, the popup dialog will still popup but the popup will have transparency and all action taken on the popup is ignored.

**Comment by rotorgames** [comment] 2017-06-16 10:41
@leeanpeng What version of popup plugin do you use?

**Comment by leeanpeng** [comment] 2017-06-17 12:20
@rotorgames  I am using the popup for xamarin form version 1.0.4. It works well when the device animation is not set to animation off. The problem arising when I tested on samsung note 5 and galaxy s7 edge runnning android 7.0. However, when I tested on samsung note 2 running android 4.4.2 with animation off, it is working perfectly.

**Comment by rotorgames** [comment] 2017-06-17 12:21
Please try to use v1.1.0-pre2

**Comment by leeanpeng** [comment] 2017-06-19 01:25
Hi, the issue is still happening, have you tested on your side? I will report to Xamarin as when i set the device animation to off, the activity indicator will not showing too.

**Comment by EmilAlipiev** [comment] 2017-06-21 14:14
my ignorance sorry but how do you set device animation off? do you mean rotation?

**Comment by leeanpeng** [comment] 2017-06-22 01:06
[http://cloud.addictivetips.com/wp-content/uploads/2017/01/android-animations.png](url)
@EmilAlipiev U can find animation setting in developer options

**Comment by rotorgames** [comment] 2017-07-12 05:43
@leeanpeng Thank you for question. I will look it soon.

**Comment by gcadmes** [comment] 2017-07-17 20:59
@rotorgames I'm having a similar problem, so I'll use this same thread as it is related to android and animation.
I'm using 1.1.0-pre2 because it addresses issues I needed fixed in iOS. So thank you for fixing several of iOS 10+ bugs.

Anyway, the following does not work in Android:
`PushPopupAsync(page, true)`

However, this does work:
`PushPopupAsync(page, false)`

So unless I explicitly tell the API to not animate the page, it works, if I specify 'true' to animate it doesn't work.

My device is a Nexus 7 running Android 6.0.1.
Have you seen this? 

May I ask how soon before 1.1.0 pre3 is released?

**Comment by gcadmes** [comment] 2017-07-17 21:48
Forgot to mention, RemovePopupPageAsync also fails if the 'animate' argument is 'true'.

**Comment by rotorgames** [comment] 2017-10-20 20:36
@gcadmes What version of Android did you test?

**Comment by rotorgames** [comment] 2018-01-30 17:11
Duplicate #159

**Closed by rotorgames** 2018-01-30 17:11 UTC
Labels: need-review

**Comment by robintschroeder** [comment] 2018-02-01 16:12
I can confirm this last build fixes the problem with the animations disabled on Android. Also regression tested on UWP and iOS, and works great. Also great excuse to update to XF 2.5.   :-)
