### ISSUE TITLE
PopAllAsync throws an exception even if catched

### ISSUE THREAD

**Issue by elisabeth-mitton** [rotorgames/Rg.Plugins.Popup#443] opened 2019-06-20 12:45 UTC
Hi,
This is a very nice plugin I enjoy using, however I get this exception, which makes my app crash (even though my code is catched)

`[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.IndexOutOfRangeException: There is not page in PopupStack
[MonoDroid]   at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass9_0.<PopAllAsync>b__0 () [0x0003d] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:90 
[MonoDroid]   at Rg.Plugins.Popup.Services.PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafty>b__0 () [0x00022] in C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:163 
[MonoDroid]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <237702a5f819427988b9a6f26fb13976>:0 
[MonoDroid]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <255228cf3ccf43dc8a3827c8cfe712ea>:0 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <255228cf3ccf43dc8a3827c8cfe712ea>:0 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <255228cf3ccf43dc8a3827c8cfe712ea>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.31(intptr,intptr)`

Thanks for any help!

**Comment by mfeingol** [comment] 2019-07-01 03:27
I'm seeing this occasionally as well. Here's the stack trace from AppCenter:

```
PopupNavigationImpl+<>c__DisplayClass8_0.<PopAsync>b__0 ()
PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafty>b__0 ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.39(intptr,intptr)
```

Doesn't seem like there's anything we can do to catch and handle this exception.

**Comment by mikepotvin** [comment] 2019-07-03 19:32
It's due to https://github.com/rotorgames/Rg.Plugins.Popup/blob/70ef35fc3758354f5a89beed26eb2aaddb196f8f/src/Rg.Plugins.Popup/Services/PopupNavigationImpl.cs#L90 

The call is invoked on main thread so it leaves the try catch scope. Resulting in an exception that can't be caught

**Comment by rotorgames** [comment] 2019-07-23 10:44
I think it was fixed in https://github.com/rotorgames/Rg.Plugins.Popup/pull/400/commits/80f4aabbe8e985dd1a239b7232bb8f9ef2071430

Try to use the last version of Development NuGet: https://ci.appveyor.com/nuget/rg-plugins-popup-p6l5elugev99 and always use `await` operator to catch all exception inside the second thread.

**Closed by rotorgames** 2019-07-23 10:44 UTC

**Comment by mfeingol** [comment] 2019-07-23 21:41
I'll note that in my case, a bug in my code was the root cause. I wasn't correctly checking for an item on the backstack before calling Pop.
