### ISSUE TITLE
PopupNavigation.PushAsync does not work with XF2.5

### ISSUE THREAD

**Issue by JKennedy24** [rotorgames/Rg.Plugins.Popup#192] opened 2017-11-20 15:36 UTC
I have the following method in my PCL:

```
Device.BeginInvokeOnMainThread(async () =>
{
   await PopupNavigation.PushAsync(popUpPage);
});
```

and have recently upgraded to the latest Xamarin.Forms 2.5.0 stable

and the method above never returns when pushing a new page with latest version.

Worked fine with previous stable Xamarin.Forms

I'm guessing it has something to do with this method: https://github.com/rotorgames/Rg.Plugins.Popup/blob/a44ace31c5b9dfa2df2cb7b1eb3200cf17e41d43/src/Rg.Plugins.Popup/Services/PopupNavigation.cs#L28

**Comment by JKennedy24** [comment] 2017-11-20 16:16
Could be down to this line actually:
https://github.com/rotorgames/Rg.Plugins.Popup/blob/a0bfde7409b540e8627edb0efda31692b0ca1994/src/Rg.Plugins.Popup.Droid/Impl/PopupNavigationDroid.cs#L24

as the 2.5.0 [release notes](https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.5/2.5.0-stable/) say:

Forms: Context is obsolete as of version 2.5. Please use a local context instead.

**Comment by Wietse-0803** [comment] 2017-11-20 21:44
How to fix this problem? Waiting until developer releases new version of this plugin?

**Comment by JKennedy24** [comment] 2017-11-21 08:47
@Wietse-0803 where did you find that quote that `popupnavigation.PopAsync(bool)` is obsolete?

**Comment by Wietse-0803** [comment] 2017-11-21 11:17
Got that message in the 1.10-pre3 version, it doesn't occur in v1.04.

**Comment by Adlbert** [comment] 2017-11-23 16:29
Same here. 
Xamarin.Forms: 2.5.0.91635
Rg.Plugins.Popup: 1.1.0-pre3


Usage:
```
var page = new MyPopupPage();
await PopupNavigation.Instance.PushAsync(page);
```

Works on iOs but not on Android.
Not getting any Output.

**Comment by rotorgames** [comment] 2017-11-25 14:07
@JKennedy24 What version of Android did you test?

**Comment by rotorgames** [comment] 2017-11-25 17:53
@JKennedy24  @Wietse-0803 @Adlbert I have tested it with a blank project with Xamarin.Forms 2.5.0.91635 and Rg.Plugins.Popup: 1.1.0-pre5 and it has worked.

You can clear your project and remove bin and obj folders from all project and try to test again. I think that it will help you.

**Comment by Wietse-0803** [comment] 2017-11-25 19:52
@rotorgames thank you. I installed v1.1.0-pre5 en it works properly with XF 2.5 👍!

**Comment by rotorgames** [comment] 2017-11-25 20:13
@Wietse-0803 Nice to hear it.

**Comment by jtomes123** [comment] 2017-11-25 23:15
Is there anything special you did? I updated everything and it stopped crashing (null ref excp), but now nothing happens when I try to open a popup like this 
`var page = new PopupPage();
 PopupNavigation.Instance.PushAsync(page);`

**Comment by rotorgames** [comment] 2017-11-26 04:22
@jtomes123 Did you invoke PushAsync with `async` modifier like this `async PopupNavigation.Instance.PushAsync(page);`?

**Comment by jtomes123** [comment] 2017-11-26 08:52
@rotorgames Ok, so it does something but a nullreferenceexception is thrown again.

`System.NullReferenceException: Object reference not set to an instance of an object
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<AddAsync>d__9.MoveNext () [0x00028] in <241c5b42c38e4199875a15fcb780e7e3>:0
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113
  at Rg.Plugins.Popup.Services.PopupNavigationImpl+<PushAsync>d__5.MoveNext () [0x00094] in <241c5b42c38e4199875a15fcb780e7e3>:0
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113
  at Projektant_Forms.MultiPickerView`1+<OpenPopUp>d__3[T].MoveNext () [0x00031] in /Users/Admin/Projects/Projektant_Forms/Projektant_Forms/MultiPicker.cs:27
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.3.0.47/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018
  at UIKit.UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIKitSynchronizationContext.cs:24
  at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/Foundation/NSAction.cs:163
  at at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:63
  at Projektant_Forms.iOS.Application.Main (System.String[] args) [0x00001] in /Users/Admin/Projects/Projektant_Forms/iOS/Main.cs:17
`

Here is the code i used:

`        public async void OpenPopUp()
        {
            await Navigation.PushPopupAsync(PopupPage);
        }`

**Comment by rotorgames** [comment] 2017-11-26 14:02
@jtomes123 Did you install the plugin to each project? All versions of popup plugin in a solution should be consolidated

**Comment by JKennedy24** [comment] 2017-11-27 10:41
@rotorgames Have updated to V1.1.0 Pre-5 but still no luck.

Now using the code:
```
                    Device.BeginInvokeOnMainThread(async () =>
                    {
                        await PopupNavigation.Instance.PushAsync(popUpPage);
                    });
```

I am running on Android 7.1 using Xamarin.Forms 2.5.0.91635.

Have cleaned and rebuilt app / even removed app from device but still no luck

**Comment by rotorgames** [comment] 2017-11-28 06:26
@JKennedy24 Can you create a simple project where you can reproduce your problem and give me?

**Comment by JKennedy24** [comment] 2017-11-28 11:08
@rotorgames I'll try get one toghether if I get time. I have also tested on Android 4 and it didn't work, so the problem is probably to do with my application in particular. No doubt it will be the UI thread blocking itself would be my guess

**Comment by brianjtools** [comment] 2017-12-02 21:08
I'm getting this on UWP release mode with either 1.04 or 1.0-5 pre.  Android works.
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Arg_NullReferenceException

Occurs both on x86 and x64 Releases.  Debug versions run okay.
Looks like for some reason the PopUp pages can't be loaded since it shows a FileNotFoundException when loading.  Odd since they load fine in Debug.

Here's a simple example which crashes in Release mode.  Is there something I'm missing?  I did download the plugin code and built it and the demos worked okay in Release mode.
[RgTest.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/1524158/RgTest.zip)

**Comment by JKennedy24** [comment] 2017-12-06 10:03
@rotorgames I downloaded the 1.1.0 branch and wanted to get the sample up and running to test this end to try reproduce.

The project references a Xamarin.Forms Version 2.4.0.283 which isn't a valid Xamarin forms nuget. I'm guessing this a custom build you have done yourself?

Would it be possible to update the 1.1.0 branch?

**Comment by WebDucer** [comment] 2017-12-11 08:23
I could solve the problem by adding the `System.Runtime.CompilerServices.Unsafe` NuGet package in version 4.3 (explicitly) to Android project.

I had in another project (with Entity Framework Core) a problem with VS 2017 15.5. And as a soltion was listed this package. I tries this in a project with the popup plugin and it works.

**Comment by JKennedy24** [comment] 2017-12-11 10:44
@WebDucer I will try that out and report whether that fixes he issue

**Comment by brianjtools** [comment] 2017-12-12 21:01
I wound up pulling the plugin from my app.  Instead took the layouts and wrapped them in a StackLayout so they appear more as a popup against a light grey full page.  Frankly I was mystified that Xamarin didn't include popups but I now think the paradigm is to make interfaces just function like the web which in many case everything is full screen even for a small form.

**Comment by JKennedy24** [comment] 2017-12-13 09:24
@WebDucer Tried adding the package. Unfortunately didn't solve the issue

**Comment by WebDucer** [comment] 2017-12-13 09:34
@JKennedy24 Did you clear all your `bin` and `obj` folders (+ restart VS)?

**Comment by JKennedy24** [comment] 2017-12-13 09:59
@WebDucer Just tried deleting all the bin / obj folders and restart VS - still same no page showing

**Comment by Cloudkasten** [comment] 2017-12-19 09:05
@rotorgames  Any news?

**Comment by rotorgames** [comment] 2017-12-19 09:20
@Cloudkasten @JKennedy24 Check this plugin is installed in each project and versions of this plugin are consolidated and after it, remove each bin and obj folders in solution and try again.

**Comment by Cloudkasten** [comment] 2017-12-19 09:36
Installed in each project.
Version: 1.1.1-pre
XF Version: 2.5.0.121934

I can confirm it works as expected! Many thanks @rotorgames !

**Comment by rotorgames** [comment] 2017-12-19 12:47
@Cloudkasten nice to hear it.

**Comment by JKennedy24** [comment] 2017-12-20 10:04
@rotorgames just tried upgrading to 1.1.1-pre with latest Xamarin Forms and still getting the same behavior.

- Call Push Async
- No Page displays

I will try get the demo this week to replicate my situation

**Comment by rotorgames** [comment] 2017-12-20 13:05
@JKennedy24 Ok. I'm waiting for it.

**Comment by JKennedy24** [comment] 2018-01-11 14:00
Ok so I managed to finally get to the bottom of this and I'm going to put a few debugging pointers here, each step is listed in things to try if the above step doesnt work move onto the next

1. So firstly upgrade to 1.1.1-pre
2. Make sure you are calling `Rg.Plugins.Popup.Popup.Init()` as outlined [here](https://github.com/rotorgames/Rg.Plugins.Popup#initialization) I don't know if this was added in a recent update but I definitely wasnt calling it.
3. On Android I use a `SplashScreen` activity which then instantiates my `MainActivity` (my `FormsActivity`). You need to call `Init()` in the `MainActivity`
4. This one is slightly more difficult. So I was using dependency injection and an interface to show my popup pages, but the methods were not `async` causing a deadlock, when using dependency injection make sure the methods are async and awaited all the way up the stack

I'm happy to close this issue, will leave @rotorgames to close off this issue

**Comment by EmilAlipiev** [comment] 2018-01-11 14:09
@JKennedy24  always try the latest pre. latest pre version works for me fine. if not, maybe you are calling init method in wrong place. please share your mainactivity

**Comment by JKennedy24** [comment] 2018-01-11 14:11
@EmilAlipiev I probably wasn't clear enough.

I have now fixed my issue using the steps outlined above. I put them on this thread to help anyone else out who may be seeing the same issue. Hope that helps

**Comment by EmilAlipiev** [comment] 2018-01-11 14:17
Cool and you can close this ticket ;) thank you

**Closed** 2018-01-11 16:56 UTC
Labels: bug, priority-high

**Comment by rotorgames** [comment] 2018-01-13 09:55
@brianjtools 
> Я получаю это в режиме выпуска UWP с 1.04 или 1.0-5 pre. Android работает. Возникло событие 
System.NullReferenceException 
HResult = 0x80004003 
Сообщение = Arg_NullReferenceException
Возникает как при выпуске x86, так и в x64. Версия отладки работает нормально. 
Похоже, что по какой-то причине страницы PopUp нельзя загружать, так как при загрузке отображается FileNotFoundException. Нечетные, так как они отлично загружаются в Debug.
Вот простой пример, который вылетает в режиме Release. Есть что-то, что мне не хватает? Я загрузил код плагина и построил его, и демонстрации работали нормально в режиме Release. 
RgTest.zip

Did you see it? https://github.com/rotorgames/Rg.Plugins.Popup/#uwp-troubleshooting
