### ISSUE TITLE
Freeze screen on Release Mode

### ISSUE THREAD

**Issue by Alextorres950325** [rotorgames/Rg.Plugins.Popup#580] opened 2020-09-18 17:20 UTC
## 🐛 Bug Report

the popup many times freezes my application, it is displayed, but it cannot be closed or receives touch events

### Expected behavior

That the popup does not freeze the application

### Reproduction steps

- pushAsync any rg.page

### Configuration
Xamarin.Forms 4.7.0.1179
Android X
iOs 13.7
**Version:** 2.0.0.5

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [X] :monkey: Xamarin.Forms

**Comment by salgiza** [comment] 2020-09-28 12:33
Any updates on this?

I just found that suddenly I have the same problem in iOS14 (unfortunately I don't currently any iOS13 devices to test whether it happens in both versions or not).

For me, it only happens when an Entry field takes focus. The popup shows correctly, and you can tap on any buttons/tap outside it to hide it. But, as soon as you tap on an entry field, you can see the cursor blinking, but you can't enter any text in it and everything stops responding.

It doesn't raise any exceptions or anything, it just stops responding to any user interaction.

Note: this only happens in iOS, Android does not show this behaviour.

**Comment by Alextorres950325** [comment] 2020-09-28 22:55
> Any updates on this?
> 
> I just found that suddenly I have the same problem in iOS14 (unfortunately I don't currently any iOS13 devices to test whether it happens in both versions or not).
> 
> For me, it only happens when an Entry field takes focus. The popup shows correctly, and you can tap on any buttons/tap outside it to hide it. But, as soon as you tap on an entry field, you can see the cursor blinking, but you can't enter any text in it and everything stops responding.
> 
> It doesn't raise any exceptions or anything, it just stops responding to any user interaction.
> 
> Note: this only happens in iOS, Android does not show this behaviour.

the behavior is random, but it happens to me on both platforms, IOs 13.6 and android X with Target SDK API 29 and xamarin forms 4.8.0.1269

**Comment by LuckyDucko** [comment] 2020-09-29 00:40
> For me, it only happens when an Entry field takes focus. The popup shows correctly, and you can tap on any buttons/tap outside it to hide it. But, as soon as you tap on an entry field, you can see the cursor blinking, but you can't enter any text in it and everything stops responding.

hey @salgiza do you have a test project I could narrow this down on? I have not met this issue before, and I use entry fields.

As an aside, if you run the rg sample project, and open the login popup, does that display the same behaviour?

**Comment by salgiza** [comment] 2020-09-29 08:18
@LuckyDucko I just downloaded the repository, run the sample project, and I found this:

* I ran the app in the iOS emulator (iPod Touch 7th generation, iOS14), and the app froze when I tapped on the "Open Popup" button, and then on the user field.
* I ran the app on my iPhone X, it worked without a hitch.
* I ran the app in the iOS emulator, using a new iPhone 11 image, it also worked perfectly.
* I deleted de iPod Touch image to start again from zero. Redeployed the app.. and it worked (!).
* I redeployed the app to the iPod Touch emulator image (the one I was using when I posted my message yesterday) and everything works fine.

The only thing I had done in the iOS image was to enable "dark mode", but I've activated it again and it does not seem to affect any of the apps, so I don't know what to think. I mean, the sample app failed the first time it was loaded into the device, so no data/cache/whatever that might have affected was there, but obviously there was something in the device image that broke it.

Unfortunately, now I can't reproduce the bug myself (!), but I'll have an eye on it to see if I can find anything that can give us any tips as to what caused that behaviour 😮

**Comment by salgiza** [comment] 2020-09-29 08:23
P.S. The weird thing is that, if as @Alextorres950325 mentions, this also happens randomly in Android, what can cause two different apps in iOS to show this behaviour until the device is reset, that can also happen in Android? 😵

**Comment by abdelbena** [comment] 2020-09-29 09:04
For me it happens only on iOS and when using Editor, if I use Entry it works fine.

**Comment by LuckyDucko** [comment] 2020-09-29 09:06
@salgiza 
Perhaps its related to Visual Studio for Mac/Xcode tooling in some form or fashion? 

@abdelbena do you have a project I could investigate?

**Comment by salgiza** [comment] 2020-09-29 09:38
@LuckyDucko 
I don't think so? I stopped the iOS simulator, I deleted the device image, but I didn't even bother to restart VS for macOS: I just stopped the debugger and pressed on the run button again after I had deleted it, to start the simulator again, so I'm not sure whether that would make any difference to VS.

And I actually debugged the sample in the simulator image were it failed, I debugged it in my phone (where it worked) and deployed it again to the simulator were it kept failing. So, at least, it was consistent in which device it failed.

I didn't think about just rebooting the simulator image, though. Maybe something that stays in memory? (But again, I don't understand why it would fail both in my app and in the sample app).

Or maybe you are right and it has something to do with VS doing something to quickly deploy the app (if it has already been deployed in the device) that is causing the problem? 🤔 
(And because the simulator had restarted it deployed the app from zero)

**Comment by Alextorres950325** [comment] 2020-10-01 17:13
It happens to me just when a contentview or contentpage changes, that is, I make a change of view, and the Rg.Page is appearing both simultaneously and before or after loading, as I say is randomly. 

Edit: 
I have detected that it always happens in release mode, in debug mode it is very unusual but it also appears

**Comment by Alextorres950325** [comment] 2020-10-13 22:16
Ok I used RelayCommand to gesturerecognizers but doesn't work, So, I changed for Command instance and works fine
it's so extrange because in Debug mode works fine, but on Release Mode, the RelayCommand doesn't work

**Comment by LuckyDucko** [comment] 2020-12-21 22:40
@Alextorres950325 if you don't have a project I can reproduce, im going to have to close this for now.
However, if this keeps happening, and you are able to track it down, feel free to @ me here, and I'll reopen

**Closed as completed by LuckyDucko** 2020-12-21 22:40 UTC
