### ISSUE TITLE
Popups no longer open correctly when in landscape mode on iOS devices.

### ISSUE THREAD

**Issue by dpannullo** [rotorgames/Rg.Plugins.Popup#606] opened 2020-11-30 17:26 UTC
## 🔙 Regression

Popups no longer open correctly when in landscape mode on iOS devices until the device is rotated back to portrait.

### Old (and correct) behavior

Popups open correctly in landscape mode.

### Current behavior

Popup is hidden until device is rotated back to portrait.

### Reproduction steps

Run the sample code, rotate to landscape and try to open a page.

### Configuration

**Version:** 2.0.0.7

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by LuckyDucko** [comment] 2020-11-30 22:02
@dpannullo this is a duplicate of #602 which has been fixed by #603 
We are just waiting for a new Nuget

**Comment by dpannullo** [comment] 2020-12-01 16:23
@LuckyDucko Ok, great thanks

**Comment by aptwebapps** [comment] 2020-12-02 17:53
I somehow missed #602 when I created #605 which I think is a dupe.

How often are new releases made to Nuget?

**Comment by LuckyDucko** [comment] 2020-12-02 22:07
Well to confirm if it is or isnt, can you try launching a popup in portrait mode, if portrait mode doesn't work, then you have found a new bug aswell.

And depends on how loudly we yell at @martijn00 I suppose :P, but I think he is waiting for some testing on the latest PR to make a new NuGet with both fixes

**Comment by aptwebapps** [comment] 2020-12-03 13:23
So it turns out the behavior is a little more complicated than I thought and I'm not sure the simplified test case I came up with covers all permutations, but I think it is the same bug as the PR referenced above fixes everything for me.

My app is just going into beta so I don't mind waiting for Nuget to catch up.

It's a very nice project, by the way.

**Comment by kadironay** [comment] 2020-12-07 22:13
Great effort! Thank you all! 

Looking forward to have the fix -_-

**Closed as completed** 2020-12-08 15:29 UTC
