### ISSUE TITLE
simple popup with webview crashes on iOS

### ISSUE THREAD

**Issue by marualderete** [rotorgames/Rg.Plugins.Popup#292] opened 2018-05-03 03:20 UTC
Hi guys, need help with something, don't know what is happening.
I have a simple popup page in my xamarin form project:

```
<StackLayout  >
            <WebView x:Name="myWebView" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            </WebView>
    </StackLayout>
```
Right now I'm passing the string url after InitializeComponent() in xaml.cs file:
`myWebView.Source = new UrlWebViewSource { Url = url};`

And I call this within a TapGestureRecognizer 
`Navigation.PushPopupAsync(new MyPopUpPage("https://my-url..."));`

and I got the following error (nothing but this on stacktrace):

> iOS[35217:341188] void _WebThreadLock(), 0x129b7b040: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

I already tried with the latest pre-release version (1.1.4.154-pre) on iOS but still has the same error.
Any clue? What am I missing? This code is working fine on Droid, only has this error on iOS

**Comment by Bejasc** [comment] 2018-05-23 04:12
I'm having the same issue.

Our use cases and version numbers are identical. 
The Popup page is passed a URL, which is then fed into a webview on the PopupPage. 

This didn't _appear_ to be an issue on 1.0.4, however I've had to update to resolve another issue that was affecting iPhone X. I've never experienced this on iOS until using the pre-release version.

**Comment by Bejasc** [comment] 2018-05-23 04:54
Update:
I can only reproduce this error on iPhone X.
I've tried multiple devices (physical and emulators) and I can only replicate the crash on iPhone X. (Both emulator and physical - running iOS 11.2 and iOS 11.3.1 respectively.

**Comment by catnais** [comment] 2018-06-12 08:49
Hi,
I'm having the same issue and I'm doing the same thing. 
The webview opens in a page but not in a popup on iPhone X.
If my popup contains only the webview, my app crashes. 
If I add a button or a label with my webview, the popup is opened with the button or the label and nothing else.

Tested on simulators and devices (iPhone 8, iPhone X, iOS 11.4)

**Comment by marualderete** [comment] 2018-06-12 14:05
Well, my temporal solution at the time was to replace the lib with a modal, and let the lib for other kind of needs that don't have a webview component.

**Comment by balaameex** [comment] 2018-07-25 14:39
I also got the crash in iPhone X,

void _WebThreadLock(), 0x138360000: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

Please let me know if any fix for this.

**Comment by balaameex** [comment] 2018-07-25 15:12
I found the solution,

If you run in main thread will solve the issue as below.

Device.BeginInvokeOnMainThread(async () =>
{
        await Navigation.PushPopupAsync(page, false);
});

Thanks

**Comment by FabriGinseng** [comment] 2018-09-25 11:13
thank you @balaameex

**Comment by waldroid** [comment] 2018-12-04 11:08
Hi,
I have the same issue with version 1.1.4.168 on iPhone X or newer device, but running on lower device with iOS 12.1 & 11.3.
After I upgraded to version 1.1.5.180, it's work on All iOS Device (include iPhone X or newer), but it's only work on iOS 12.1 or newer. On the version 11.3 become crash with the same issue.

Any solutions for this issue? 

Thanks

**Comment by rotorgames** [comment] 2018-12-04 11:22
@waldroid Did you see the comment of @balaameex ?

**Comment by waldroid** [comment] 2018-12-05 02:15
@rotorgames yes, I see. I've been tried that @balaameex suggested.

Device.BeginInvokeOnMainThread(async () =>
{
    await Navigation.PushPopupAsync(new ActivityIndicatorPage());
});

but still not work for me.

Thanks.

**Comment by PAFleche** [comment] 2019-01-18 16:32
I got the same crash with the solution giver by @balaameex :

```
            Device.BeginInvokeOnMainThread(async () =>
            {
                await PopupNavigation.Instance.PushAsync(webPopupView);
            });
```

**Comment by PAFleche** [comment] 2019-01-21 10:43
For information, it seems that the size of the Webview in the popup page can cause the crash.
For example :

This PopupPage **crash** :
```
<?xml version="1.0" encoding="UTF-8"?>
<controls:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls ="clr-namespace:BeautyMix.AppMobile.Core.Controls"
             xmlns:ext="clr-namespace:BeautyMix.AppMobile.Core.Extensions"
             xmlns:pp="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             x:Class="BeautyMix.AppMobile.Core.Views.PopupsViews.WebPopupView"
             Padding="25">

    <AbsoluteLayout HorizontalOptions="Fill" VerticalOptions="Fill" >
        <controls:LoadingCookieWebView x:Name="WebView" AbsoluteLayout.LayoutBounds="0, 0, 1, 1" AbsoluteLayout.LayoutFlags="All" />
        <controls:ImageButton x:Name="ButtonClose" ImageSource="ic_close_ronded.png"
                              AbsoluteLayout.LayoutBounds="1, 0, 30, 30" AbsoluteLayout.LayoutFlags="PositionProportional" />
    </AbsoluteLayout>

</controls:PopupPage>
```

While this on **doesn't crash** (I just add a margin on the webview) :
```
<?xml version="1.0" encoding="UTF-8"?>
<controls:PopupPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:controls ="clr-namespace:BeautyMix.AppMobile.Core.Controls"
             xmlns:ext="clr-namespace:BeautyMix.AppMobile.Core.Extensions"
             xmlns:pp="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup"
             x:Class="BeautyMix.AppMobile.Core.Views.PopupsViews.WebPopupView"
             Padding="25">

    <AbsoluteLayout HorizontalOptions="Fill" VerticalOptions="Fill" >
        <controls:LoadingCookieWebView x:Name="WebView" AbsoluteLayout.LayoutBounds="0, 0, 1, 1" AbsoluteLayout.LayoutFlags="All" **Margin="15"**/>
        <controls:ImageButton x:Name="ButtonClose" ImageSource="ic_close_ronded.png"
                              AbsoluteLayout.LayoutBounds="1, 0, 30, 30" AbsoluteLayout.LayoutFlags="PositionProportional" />
    </AbsoluteLayout>

</controls:PopupPage>
```

**Comment by rotorgames** [comment] 2019-01-25 04:22
I still don't get a stack trace or other information to fix it. I think this bug happens not because of the plugin. If you still have the issue, don't be afraid to open this issue again.

**Closed by rotorgames** 2019-01-25 04:22 UTC
Labels: need-review, priority-high

**Comment by Nandulucky** [comment] 2019-04-08 07:29
I added Margin=15 @PAFleche but still having same issue.

**Comment by chuvakpavel** [comment] 2019-04-09 15:05
@Nandulucky Try this https://devblogs.microsoft.com/xamarin/making-ios-11-even-easier-xamarin-forms/ this solved my issue
