### ISSUE TITLE
Doesn't show popup if application is paused and then resumed

### ISSUE THREAD

**Issue by wattsdeveloper** [rotorgames/Rg.Plugins.Popup#213] opened 2018-01-03 15:09 UTC
Using the latest pre-released version: 1.1.3.73-pre

If I run my application on Android,
then pressed back button -> application goes to paused mode
after that I resume back and cannot show any popup windows anymore.

It simply never returned from `await _navigation.PushPopupAsync(page);`
(_The only difference from the examples I can see is that we use `FormsAppCompatActivity`,
NOT `FormsApplicationActivity`, not sure if it can be a problem_)

Then if I tap back button, nothing is happening. Tap it again (second time), get exception:
```
01-03 17:05:11.009 I/MonoDroid(11178): System.InvalidOperationException: Sequence contains no elements
01-03 17:05:11.009 I/MonoDroid(11178):   at System.Linq.Enumerable.Last[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <65f4a23934a3468fae9abe3139b55169>:0 
01-03 17:05:11.009 I/MonoDroid(11178):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.HandleBackPressed (System.Object sender, System.EventArgs e) [0x0000a] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:281 
01-03 17:05:11.009 I/MonoDroid(11178):   at (wrapper delegate-invoke) <Module>:invoke_bool_object_EventArgs (object,System.EventArgs)
01-03 17:05:11.009 I/MonoDroid(11178):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnBackPressed () [0x00000] in D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:63 
01-03 17:05:11.009 I/MonoDroid(11178):   at Android.App.Activity.n_OnBackPressed (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <c8cab2efd85f442389020057942eca89>:0 
01-03 17:05:11.009 I/MonoDroid(11178):   at (wrapper dynamic-method) System.Object:fe9499a8-27c1-4801-821e-2260ccec42ec (intptr,intptr)
01-03 17:05:11.018 I/System.out(11178): (HTTPLog)-Static: isSBSettingEnabled false
```

**Comment by rotorgames** [comment] 2018-01-04 11:13
@wattsdeveloper Hi. Did you init this plugin in the OnCreate method?

**Comment by wattsdeveloper** [comment] 2018-01-04 11:18
@rotorgames yes

```
protected override void OnCreate(Bundle bundle)
{
      Popup.Init(this, bundle);
      Forms.Init(this, bundle);
}
```

**Comment by rotorgames** [comment] 2018-01-04 11:39
@wattsdeveloper Did you show a popup before back button tapping?

**Comment by rotorgames** [comment] 2018-01-04 11:50
@wattsdeveloper P.S. Can you create a project where you have reproduced this problem for an example?

**Comment by wattsdeveloper** [comment] 2018-01-04 11:51
@rotorgames no, just running the app and press back button. After resume - yes, I clicked to show the popup, but nothing is happening and on second click I get exception. 

I can try of course to reproduce it on empty project.

**Comment by rotorgames** [comment] 2018-01-04 11:53
@wattsdeveloper If you can do it that it will be super.

**Comment by wattsdeveloper** [comment] 2018-01-04 11:59
@rotorgames btw, when after I click to show the popup after resuming and press back button for the first time I can see that `PopupNavigation.Instance.PopupStack` still contains my popup page,
on second back button press it is empty.

**Comment by rotorgames** [comment] 2018-01-04 12:02
@wattsdeveloper I understood a source of the problem but I can't reproduce it in the demo project. So I ask you to create an empty project with this problem.

**Comment by wattsdeveloper** [comment] 2018-01-08 09:50
@rotorgames thank you for your response. It seems that I found issues in our code :/ and now it seems to be working as expected :)

**Comment by rotorgames** [comment] 2018-01-09 11:37
@wattsdeveloper Nice to hear it. Can I close this issue?

**Comment by swapnil591** [comment] 2018-01-10 11:44
Getting same problem @wattsdeveloper  can i know how you solve this problem

**Comment by EmilAlipiev** [comment] 2018-01-10 17:11
yes, can you please share your solution?

**Comment by swapnil591** [comment] 2018-01-13 09:27
Showing Popup using following code in page code behind
 await PopupNavigation.Instance.PushAsync(new PopUpPage());

Pop page using following code in PopUpPage() viewmodel
 await PopupNavigation.Instance.PopAsync(false);
 Messenger.Default.Send<String>("Pop", "Popnewitem");

it works well but after pause and resume app popup pop successfully but it halt exceution of below lines.

Tried debug on PopAsync(false)  it halt debugging and not execute next lines.

**Comment by rotorgames** [comment] 2018-01-13 10:17
@swapnil591 @wattsdeveloper I have changed some code recently so you can have some problem with it. I have added code which remove each popup pages from PopupStack when the Init method is invoked. I had to do it because Xamarin.Android doesn't remove static fields from memory when an application is sleeping because of it the PopupStack is not cleaned and you can see old pages which there are not in the display but there are in the PopupStack after an application has been resumed.

**Comment by swapnil591** [comment] 2018-01-13 10:39
Is there any way to display such popup after resume or will in future release or need to reduce plugin to back 1.0.4 .

**Comment by rotorgames** [comment] 2018-01-13 10:44
@swapnil591 I think that it must work. You should be able to open a new page after an application resuming. I will review it and will fix it soon

**Comment by rotorgames** [comment] 2018-01-30 12:14
@wattsdeveloper @swapnil591 Do you have this problem with the last beta builds?

**Comment by rotorgames** [comment] 2018-01-30 16:55
@swapnil591 You are welcome.

**Closed by rotorgames** 2018-01-30 16:55 UTC
Labels: bug, need-review
