### ISSUE TITLE
App not responding when open popup on Xamarin 5.0 above, issues happend only iOS version

### ISSUE THREAD

**Issue by nhuy-ecotech** [rotorgames/Rg.Plugins.Popup#664] opened 2021-04-09 06:53 UTC
## 🐛 Bug Report

App not responding when open popup on Xamarin Form 5.0 above, issues happend only iOS version. Please fix it.
### Configuration
Xamarin Form version 5.0 above

**Version:** 1.x

**Platform:** 
- :iphone: iOS

**Comment by cribia** [comment] 2021-04-09 07:34
I've got the same problem only **App Forms Shell.**
After updating Xamarin Forms the popup opens badly and when Close the last PopupPage int the PopupStack, the App crashing. Only iOS

**Comment by LuckyDucko** [comment] 2021-04-11 22:46
@nhuy-ecotech have you tried updating to latest to fix the issue?

@cribia could you please provide a zipped project recreating the issue that I could troubleshoot the issue on? thank you

**Comment by cribia** [comment] 2021-04-13 07:47
[AppPopupTestShell.zip](https://github.com/rotorgames/Rg.Plugins.Popup/files/6302051/AppPopupTestShell.zip)
In the zipped project I sent, in ItemViewModel the pop up opens correctly (PushAsync) but in closing the pop up (PopAllAsync) crashing app.
the real project is much bigger so I have extrapolated the problem into a basic project.
The problem occurred after automatic update of xamarin.
Visual Studio for Mac 2019 version 8.9
Xamarin iOS version 14.14.2

**Comment by LuckyDucko** [comment] 2021-04-14 05:21
hey @cribia while I could replicate your app crashing (froze for me), I updated the demo project for RG to test if it was latest xamarin fault, and it seemed to work fine. 

When I traced it using your app, 
first, I found an issue at awaiting a view controller being dismissed (something out of our control)
I switched this to what I assumed was the synchronous version and it passed that area, but still froze.

I think it may have something to do with how your popups are setup with ViewModels and whatnot.
If you want popups that return values asynchronously, may I shamelessly promote [my nuget](https://github.com/LuckyDucko/AwaitablePopups) designed to help with that (open issues if something is broken, as I use this on my production app!) 
Are you able to make an example of this crash using basic popups?

**Comment by ederjbezerra** [comment] 2021-04-27 18:44
Same issue here but not only iOS. Android also presents same problem.

**Comment by LuckyDucko** [comment] 2021-04-27 22:57
@ederjbezerra could you provide an example project, or are you using @cribia's

**Comment by ederjbezerra** [comment] 2021-04-28 00:47
> @ederjbezerra could you provide an example project, or are you using @cribia's

It's not cribia's project and it's a big project of one of my costumers, with almost 200mb, so it's complicated to share, I would have to take off a lot of code(I don't have much time nowadays). But here is what I'm using to reproduce the problem:

Android 11  physical device(galaxy S20+):
- Xamarin.Forms 4.7.0.1080
- Rg.Plugins.Popup  2.0.0.11

iOS 14.4.2 physical device:
- Xamarin.Forms 5.0.0.2012
- Rg.Plugins.Popup  2.0.0.11

If you push / pop some times repeatedly it freezes the application.
```
if (Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Count > 0)
   await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAllAsync();
```

Removing these two lines above makes app freeze on iOs at first or second page push, but with these lines it works for 4/5 times before freeze app.

Then, after the if:
```
await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PushAsync(new SharePage(UserID));
```

**Comment by LuckyDucko** [comment] 2021-04-28 03:25
@ederjbezerra 

Perhaps this is a threading issue, I could try and recreate this issue using the demo project, I just have some more questions

When you call the first snippet, is the assumption that you would have more than 1 page on the stack? or just 1 and greater?

Have you tried seeing if the crash happens if you remove the use of PopAllAsync, and instead go for something like a 
foreach() which would just call await Instance.PopAsync?

Also, can you see if the crash happens when there is only 1 page on the popupstack?

I have some suspicions looking through the code of PopAllAsync and I'm wondering if deadlocks come forth because of the way it has been created.

**Comment by ederjbezerra** [comment] 2021-04-28 12:23
> @ederjbezerra
> 
> Perhaps this is a threading issue, I could try and recreate this issue using the demo project, I just have some more questions
> 
> When you call the first snippet, is the assumption that you would have more than 1 page on the stack? or just 1 and greater?
> 
> Have you tried seeing if the crash happens if you remove the use of PopAllAsync, and instead go for something like a
> foreach() which would just call await Instance.PopAsync?
> 
> Also, can you see if the crash happens when there is only 1 page on the popupstack?
> 
> I have some suspicions looking through the code of PopAllAsync and I'm wondering if deadlocks come forth because of the way it has been created.

Bingo! Using foreach and popping each page solves the problem. And yes, having just one page also presents this issue.

**Comment by LuckyDucko** [comment] 2021-04-28 22:03
Excellent, okay, so there is definitely something up with PopAllAsync. I'll look into it closer, glad i could help

**Comment by draganDBL** [comment] 2021-05-21 12:56
I have same problem on my iOS device , when trying to open pop up app just freez.

**Comment by nchrisr** [comment] 2021-06-11 16:54
How were you able to work around this? I am currently having this issue, and I am thinking to downgrade my Xamarin.Forms version, is this what you did?

**Comment by LuckyDucko** [comment] 2021-06-14 23:34
@Kikanye So, if you use PopAllAsync, instead see if you could use

```csharp
            foreach (var popupPage in Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack)
            {
                await Rg.Plugins.Popup.Services.PopupNavigation.Instance.RemovePageAsync(popupPage);
            }

```
OR you could use the following as well, I haven't tested it but its the same idea
```csharp
            for (int stackCount = Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Count; stackCount > 0; stackCount--)
            {
                await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAsync();
            }
```

**Comment by darrabam** [comment] 2021-07-03 12:28
> @Kikanye So, if you use PopAllAsync, instead see if you could use
> 
> ```cs
>             foreach (var popupPage in Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack)
>             {
>                 await Rg.Plugins.Popup.Services.PopupNavigation.Instance.RemovePageAsync(popupPage);
>             }
> ```
> 
> OR you could use the following as well, I haven't tested it but its the same idea
> 
> ```cs
>             for (int stackCount = Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.Count; stackCount > 0; stackCount--)
>             {
>                 await Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopAsync();
>             }
> ```

@LuckyDucko enumerating the stack with foreach and modifying its content will raise a System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute.'

a simple workaround is to call ToList() which will copy the values to a separate list
`            foreach (var popupPage in Rg.Plugins.Popup.Services.PopupNavigation.Instance.PopupStack.ToList())
            {
                await Rg.Plugins.Popup.Services.PopupNavigation.Instance.RemovePageAsync(popupPage);
            }`

**Comment by LuckyDucko** [comment] 2021-07-04 23:34
Ah, good point @darrabam, didn't give it too much thought as @ederjbezerra thought it fine, but I assume he tinkered it similar to what you had it.

I think I am going to change it to
```csharp
while (PopupNavigation.Instance.PopupStack.Count > 0)
{
    await PopupNavigation.Instance.PopAsync(false);
}
```

As it seems the simplest way to go about it.

While the current way uses

```csharp
var popupTasks = PopupStack.ToList().Select(page => RemovePageAsync(page, animate));
return Task.WhenAll(popupTasks);
```
It does seem to have an issue here or there.

**Closed as completed** 2021-07-14 02:36 UTC
Labels: bug

**Comment by djhvscf** [comment] 2022-01-29 22:18
This is still not working for me. I had to downgrade to 2.0.0.7
