### ISSUE TITLE
Crashes on ios13

### ISSUE THREAD

**Issue by nabilakhlaque** [rotorgames/Rg.Plugins.Popup#468] opened 2019-09-26 22:15 UTC
Since I updated to ios13, app seems to crash every now and then.
To reproduce, open-close popup fast 2-3 times, then it crashes.

This is my stacktrance, can anyone please look at it?

`    PopupPlatformIos.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup.IOS\Impl\PopupPlatformIos.cs:73
    PopupNavigationImpl.RemoveAsync (Rg.Plugins.Popup.Pages.PopupPage page) C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:134
    PopupNavigationImpl+<>c__DisplayClass10_0.<RemovePageAsync>b__0 () C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:115
    PopupNavigationImpl+<>c__DisplayClass15_0.<InvokeThreadSafty>b__0 () C:\projects\rg-plugins-popup\src\Rg.Plugins.Popup\Services\PopupNavigationImpl.cs:163
    AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/external/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021
    NSAsyncSynchronizationContextDispatcher.Apply () /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:178
    (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
    UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:86
    UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:65
    Application.Main (System.String[] args) C:\Users\Nabil Akhlaque\Source\Repos\Orienta\Orienta\Orienta.iOS\Main.cs:17`

**Comment by gutierrezralph** [comment] 2019-09-27 02:37
Update your Mac Machine to OS 13
Update XCode
Update your Xamarim.Forms > Clean > Build > Test

I hope it helps :)

**Comment by JFMG** [comment] 2019-09-27 07:17
This issue is a duplicate of https://github.com/rotorgames/Rg.Plugins.Popup/issues/459

**Comment by nabilakhlaque** [comment] 2019-09-27 08:51
I have done, but still same issue.

**Comment by rotorgames** [comment] 2019-10-03 06:03
Duplicate #459

**Closed by rotorgames** 2019-10-03 06:03 UTC
